name 'ram-cookbook'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ram-cookbook'
long_description 'Installs/Configures ram-cookbook'
version '0.1.0'
